### ISSUE TITLE
Additional icons

### ISSUE THREAD

**Issue by romanskorobagatko** [SoichiroYamane/sketchybar-app-font-bg#1]
Hello. Please add additional icons for: [Vivaldi](https://vivaldi.com/download/), [Drafts](https://getdrafts.com/), [qBittorrent](https://www.qbittorrent.org/), [DEVONthink](https://www.devontechnologies.com/apps/devonthink), [Filen Drive](https://filen.io/), [Cockos Reaper](https://www.cockos.com/reaper/), [Ableton Live](https://www.ableton.com/), [Bitwig Studio](https://www.bitwig.com/).

**Comment by SoichiroYamane** [comment]
Thanks. I will create them later!

**Comment by SoichiroYamane** [comment]
I added these icons: ab30b347b749e3f0dab810e346ce29f00c80aa1f
Can you check following lists?
1. designs of icons are okay? If these is mistake, can you provide proper image of icon?
2. Using @SoichiroYamane/dotfiles/sketchybar/icon_updater.sh, can you update icons?
3. Icons are properly rendered when all requested app are open?
4. Visibility of icons on sketchybar is fine?

If you have any trouble, please feel free to ask me!

**Comment by romanskorobagatko** [comment]
1. All good
2. Icons updated successfully
3. All icons rendered fine
4. All the icons visible except Reaper DAW one, it doesn’t pick up this app.

Could you also add Brave browser please?

Thank you

**Comment by SoichiroYamane** [comment]
Hi! Sounds nice!
4. I suppose that you mean icon of Reaper DAW([Cockos Reaper](https://www.cockos.com/reaper/)) does now show on the bar. The possible reason is the registered name of the app is different from the actual one.
  1. What you can tentatively try is modifying the map of Reaper DAW (Cockos Reaper) in ~/.config/sketchybar/helpers/icon_map.lua: line 24
  ```lua
        -- Change registered name: Cockos Reaper -> Reaper DAW
  	["Reaper DAW"] = ":cockos_reaper:", -- do not change :cockos_reaper: which is mapped to icon font
  ```
  2. Reload the sketchybar, and see that the reaper icon is properly rendered when the app opens. If not, you need to find the proper name of the app and do first step again.
If you succeed it, can you tell me the proper name of the app? I can modify the map. Or you can make PR for that.

> Could you also add Brave browser please?

Sure! I will make it tomorrow.

**Comment by romanskorobagatko** [comment]
I figured out the proper name and it worked, the name should be uppercase - "REAPER". 

Thanks a lot!

**Comment by SoichiroYamane** [comment]
Very nice! I merged PR for this issue: 379195ca4dda4d91ef910f731d406e31c258f27b

**Comment by romanskorobagatko** [comment]
Could you please add [CotEditor](https://coteditor.com/) icon as well?

**Comment by SoichiroYamane** [comment]
I added your requested icons. Can you also check them?

**Comment by romanskorobagatko** [comment]
I can confirm all of the icons are working. Btw Devonthink icon will work with the name "DEVONthink 3" in icon_map.lua file.

Thank you.

**Comment by SoichiroYamane** [comment]
Thanks for your report! I will fix it.

**Comment by romanskorobagatko** [comment]
"Ableton Live" should be "Live" for the icon to display properly.
