### ISSUE TITLE
Modifying widgets

### ISSUE THREAD

**Issue by romanskorobagatko** [SoichiroYamane/sketchybar-app-font-bg#2]
1. How to properly remove a battery widget? (since I’m on Mac Studio and don’t need it)
2. Which files I should edit to make "memory" and "wifi" widgets show the data? Currently those are empty.
3. How to change the date to AM/PM (it is showing time like "17:41" instead of "5:41")

**Comment by SoichiroYamane** [comment]
Can you open this issue in my dotfiles repository?
